services:
    syncthing:
        image: linuxserver/syncthing:latest
        container_name: syncthing
        hostname: syncthing
        environment:
            PUID: 1000
            PGID: 1000
            TZ: America/Sao_Paulo
        volumes:
            - $HOME/home_server/syncthing/config:/config
            - $HOME/home_server/syncthing/data:/data
        ports:
            - 8384:8384
            - 22000:22000/tcp
            - 22000:20000/udp
            - 21027:21027/udp
        restart: unless-stopped
